name: Deploy Medusa to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: projects/medusa-backend
  ECS_CLUSTER: medusa-cluster
  ECS_SERVICE: medusa-server
  CONTAINER_NAME: medusa-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::612443913962:role/Github-Actions-medusa
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push docker image with updated code to ECR
        env:
          ECR_REGISTRY: 612443913962.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: New ECS deployment using updated docker image
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
